### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by phairplay** [Bahnburner/Home-Assistant-Config#3]
Hi,
I've just brought a Rpi3 to get into home assistant and being a complete noob it's hard to know where to start.
I've come across your set up as I was looking for away to add harmony. 

Would I be able to replace my setting with yours and edit where required?

Also do you have any tips?

Cheer

**Comment by Bahnburner** [comment]
You absolutely can. There's instructions and a discussion in [this thread](https://community.home-assistant.io/t/logitech-harmony-integration-with-ianddays-component/6183/59?u=bahnburner) on the home-assistant community forum. 

When you update the ```input_select``` with your activity names, make sure you do not remove the "select input" option or the automations to change the activity will not work.
