### ISSUE TITLE
API Key in code

### ISSUE THREAD

**Issue by chriskacerguis** [Bahnburner/Home-Assistant-Config#5]
Hey.

Just an FYI - Looks like you have left your API key is this file: https://github.com/Bahnburner/Home-Assistant-Config/blob/master/configuration/sensor.yaml#L19 it might be other places too...but, I was looking at your configs for it's good ideas :)

**Comment by Bahnburner** [comment]
Oh crap. Thank you for that. Let me go revoke that API key real quick.
